# Generated by Django 5.0.1 on 2024-01-07 15:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_authorpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorpage",
            name="AuthorDescription",
            field=wagtail.fields.RichTextField(
                blank=True, default="Enter description here"
            ),
        ),
    ]
