# Generated by Django 5.0.1 on 2024-01-07 15:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_authorpage_authordescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookpage",
            name="bookDescription",
            field=wagtail.fields.RichTextField(
                blank=True, default="enter description here", null=True
            ),
        ),
    ]
