# Generated by Django 5.0.1 on 2024-01-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_bookpage_bookdescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorpage",
            old_name="AuthorDescription",
            new_name="authorDescription",
        ),
        migrations.RenameField(
            model_name="authorpage",
            old_name="AuthorName",
            new_name="authorName",
        ),
    ]
