# Generated by Django 5.0.1 on 2024-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_bookpage_bookpublishedon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorpage",
            name="authorName",
            field=models.CharField(default="New Author", max_length=30),
        ),
    ]
